### ISSUE TITLE
Proměnná `i` vznikne a roste, ale nikde se nepoužije

### ISSUE THREAD

**Issue by xtompok** [paulusob/du02_barbora_paulusova#12]
Takže je možné se jí zbavit.

**Comment by paulusob** [comment]
To bylo myšleno u toho sedmidenního průtoku? Ta má být použita u výsledku - byla tam místo toho chybně použita 7.
Má tam být vysledek=kumul_prutok/i (řádek 108)

**Comment by xtompok** [comment]
Típ pádem toto je vyřešené.
