### ISSUE TITLE
Proč musíme číst vstupní soubor jen abychom získali první řádek?

### ISSUE THREAD

**Issue by xtompok** [paulusob/du02_barbora_paulusova#16]
První řádek lze snadno získat při druhém čtení souboru, není potřeba dělat celou mašinérii dvakrát.

**Comment by paulusob** [comment]
Nějak nemůžu přijít na to, jak to udělat, protože potřebuju ten získaný rok s něčím porovnávat. Kdybych ho rovnou přiřadila do obou proměnných (rok_n a rok), tak by to pak nefungovalo pro další řádky. Můžu poprosit o radu?
